
#add_definitions(-DMAX_RENDER_PASSES=${MAX_VIEWS})
#ADD_DEFINITIONS(-DNBLAS -DUSE_GKREGEX)
#
#
#add_definitions(-DENGINE_DIRECTORY="${PROJECT_SOURCE_DIR}" -DSHADER_INCLUDE_DIRECTORY="${BGFX_DIR}/src")
#
